#!/usr/bin/env python3
"""
IRN Mockup Email Sender
=======================
Emails an HTML mockup file to eitanbarzeski@gmail.com via Gmail SMTP.

Usage:
    python3 scripts/send_mockup.py <path_to_html_file>

Requirements:
    Set GMAIL_APP_PASSWORD in your environment (one-time setup).
    See scripts/setup_gmail_creds.py for help.
"""

import os
import sys
import smtplib
import base64
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from pathlib import Path

RECIPIENT = "eitanbarzeski@gmail.com"
SENDER    = "eitanbarzeski@gmail.com"
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 465


def build_email_body(html_content: str, timestamp: str, filename: str) -> str:
    """Wrap the mockup HTML in a clean email body."""
    return f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body {{ font-family: -apple-system, Helvetica, Arial, sans-serif; background: #08080f; color: #fff; margin: 0; padding: 24px; }}
  .header {{ margin-bottom: 24px; }}
  .badge {{ display: inline-block; background: rgba(176,156,240,0.15); color: #B09CF0; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; letter-spacing: 1px; text-transform: uppercase; }}
  h1 {{ font-size: 28px; font-weight: 800; letter-spacing: -0.5px; margin: 8px 0 4px; }}
  .sub {{ color: rgba(255,255,255,0.4); font-size: 13px; }}
  .divider {{ height: 1px; background: rgba(255,255,255,0.08); margin: 20px 0; }}
  .screens-label {{ font-size: 11px; font-weight: 700; color: rgba(255,255,255,0.3); letter-spacing: 2px; text-transform: uppercase; margin-bottom: 12px; }}
  .screen-chips {{ display: flex; gap: 8px; flex-wrap: wrap; }}
  .chip {{ background: rgba(255,255,255,0.06); border: 1px solid rgba(255,255,255,0.09); border-radius: 8px; padding: 6px 12px; font-size: 13px; color: rgba(255,255,255,0.7); }}
  .cta {{ margin-top: 24px; display: inline-block; background: #B09CF0; color: #fff; padding: 12px 24px; border-radius: 12px; font-size: 14px; font-weight: 600; text-decoration: none; }}
  .footer {{ margin-top: 32px; font-size: 11px; color: rgba(255,255,255,0.2); }}
</style>
</head>
<body>
  <div class="header">
    <span class="badge">IRN · Auto-generated</span>
    <h1>App Mockup</h1>
    <div class="sub">{timestamp}</div>
  </div>
  <div class="divider"></div>
  <div class="screens-label">Screens included</div>
  <div class="screen-chips">
    <div class="chip">Login</div>
    <div class="chip">Dashboard</div>
    <div class="chip">Active Workout</div>
    <div class="chip">Log</div>
    <div class="chip">Profile</div>
  </div>
  <div class="divider"></div>
  <p style="color:rgba(255,255,255,0.55);font-size:14px;line-height:1.6;">
    The full interactive mockup is attached as <strong>{filename}</strong>.
    Open it in any browser to view all screens.
  </p>
  <div class="footer">
    Generated by IRN /mockup command · branch: claude/update-branding-fix-bugs-XpfLH
  </div>
</body>
</html>
"""


def send_mockup(html_path: str):
    path = Path(html_path)
    if not path.exists():
        print(f"❌ File not found: {html_path}")
        sys.exit(1)

    password = os.environ.get("GMAIL_APP_PASSWORD", "").strip()
    if not password:
        print("❌ GMAIL_APP_PASSWORD is not set.")
        print()
        print("Run the one-time setup:")
        print("  python3 scripts/setup_gmail_creds.py")
        print()
        print("Or set it manually:")
        print("  export GMAIL_APP_PASSWORD='xxxx xxxx xxxx xxxx'")
        print()
        print("In Claude Code cloud, set it with:")
        print("  claude config set env.GMAIL_APP_PASSWORD 'xxxx xxxx xxxx xxxx'")
        sys.exit(1)

    html_content = path.read_text(encoding="utf-8")
    filename     = path.name
    timestamp    = datetime.now().strftime("%b %d, %Y at %H:%M")

    # Build message
    msg = MIMEMultipart("mixed")
    msg["Subject"] = f"IRN Mockup — {timestamp}"
    msg["From"]    = SENDER
    msg["To"]      = RECIPIENT
    msg["X-IRN-Mockup"] = "1"

    # Alternative body (plain + HTML)
    alt = MIMEMultipart("alternative")
    alt.attach(MIMEText(
        f"IRN Mockup generated {timestamp}.\nOpen the attached HTML file in a browser to view.",
        "plain"
    ))
    alt.attach(MIMEText(build_email_body(html_content, timestamp, filename), "html"))
    msg.attach(alt)

    # Attach the full HTML file
    att = MIMEBase("text", "html")
    att.set_payload(html_content.encode("utf-8"))
    encoders.encode_base64(att)
    att.add_header(
        "Content-Disposition",
        "attachment",
        filename=filename
    )
    msg.attach(att)

    # Send
    print(f"📤 Sending mockup to {RECIPIENT}...")
    try:
        with smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) as server:
            server.login(SENDER, password)
            server.sendmail(SENDER, RECIPIENT, msg.as_string())
        print(f"✅ Sent: {filename} → {RECIPIENT}")
    except smtplib.SMTPAuthenticationError:
        print("❌ Gmail auth failed. Check your app password.")
        print("   Make sure 2-Step Verification is on and you're using an App Password.")
        print("   Get one at: https://myaccount.google.com/apppasswords")
        sys.exit(1)
    except Exception as e:
        print(f"❌ Send failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 scripts/send_mockup.py <path_to_html>")
        sys.exit(1)
    send_mockup(sys.argv[1])
